os:
    - linux
    - osx
env:
    - SWIFT_VERSION=4.0
    - SWIFT_VERSION=4.1
osx_image: xcode9
language: generic
sudo: required
dist: trusty
install:
    - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
script:
    - swift test
