language: swift

branches:
 only:
 - master

xcode_project: ShellOut.xcodeproj
xcode_scheme: ShellOut-package
osx_image: xcode9.3
xcode_sdk: iphonesimulator11.3

script: 
 - xcodebuild -scheme ShellOut-package -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone X,OS=11.3' test
 